/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MgDrawer {
        "drawerTitle": string;
        "open": () => Promise<void>;
        "opened": boolean;
    }
    interface MgTooltip {
        "tooltipInfo": string;
    }
}
declare global {
    interface HTMLMgDrawerElement extends Components.MgDrawer, HTMLStencilElement {
    }
    var HTMLMgDrawerElement: {
        prototype: HTMLMgDrawerElement;
        new (): HTMLMgDrawerElement;
    };
    interface HTMLMgTooltipElement extends Components.MgTooltip, HTMLStencilElement {
    }
    var HTMLMgTooltipElement: {
        prototype: HTMLMgTooltipElement;
        new (): HTMLMgTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "mg-drawer": HTMLMgDrawerElement;
        "mg-tooltip": HTMLMgTooltipElement;
    }
}
declare namespace LocalJSX {
    interface MgDrawer {
        "drawerTitle"?: string;
        "opened"?: boolean;
    }
    interface MgTooltip {
        "tooltipInfo"?: string;
    }
    interface IntrinsicElements {
        "mg-drawer": MgDrawer;
        "mg-tooltip": MgTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mg-drawer": LocalJSX.MgDrawer & JSXBase.HTMLAttributes<HTMLMgDrawerElement>;
            "mg-tooltip": LocalJSX.MgTooltip & JSXBase.HTMLAttributes<HTMLMgTooltipElement>;
        }
    }
}
